package converter

import (
	"bytes"
	"fmt"

	"github.com/justin/recipe/internal/formats/np3"
	"github.com/justin/recipe/internal/formats/xmp"
	"github.com/justin/recipe/internal/models"
)

// Supported format identifiers
const (
	FormatNP3 = "np3"
	FormatXMP = "xmp"
)

// NP3 magic bytes (first 3 bytes: "NCP" in ASCII)
var np3MagicBytes = []byte{'N', 'C', 'P'}

// Convert performs bidirectional conversion between supported photo editing recipe formats.
//
// It orchestrates the conversion flow: validate → parse → generate → wrap errors.
// The function is thread-safe and stateless, allowing concurrent conversions without race conditions.
//
// Supported formats:
//   - "np3": Nikon Picture Control binary format
//   - "xmp": Adobe Lightroom CC/Camera Raw XML format
//
// Supported conversions: NP3 ↔ XMP (2 conversion paths)
//
// Parameters:
//   - input: Raw bytes of the source format file
//   - from: Source format identifier ("np3" or "xmp"). Use empty string for auto-detection.
//   - to: Target format identifier ("np3" or "xmp")
//
// Returns:
//   - []byte: Generated bytes in the target format
//   - error: ConversionError with operation context, or nil on success
//
// Performance: Target <100ms per conversion, <5ms hub overhead
//
// Example:
//
//	np3Data, err := os.ReadFile("recipe.np3")
//	xmpData, err := converter.Convert(np3Data, "np3", "xmp")
//	if err != nil {
//	    var convErr *ConversionError
//	    if errors.As(err, &convErr) {
//	        fmt.Printf("Failed during %s: %v\n", convErr.Operation, convErr.Cause)
//	    }
//	}
func Convert(input []byte, from, to string) ([]byte, error) {
	// Auto-detect source format if not specified
	if from == "" {
		detectedFormat, err := DetectFormat(input)
		if err != nil {
			return nil, &ConversionError{
				Operation: "detect",
				Format:    "unknown",
				Cause:     err,
			}
		}
		from = detectedFormat
	}

	// Validate format strings
	if err := validateFormat(from); err != nil {
		return nil, &ConversionError{
			Operation: "validate",
			Format:    from,
			Cause:     err,
		}
	}
	if err := validateFormat(to); err != nil {
		return nil, &ConversionError{
			Operation: "validate",
			Format:    to,
			Cause:     err,
		}
	}

	// Parse input to UniversalRecipe
	var recipe *models.UniversalRecipe
	var err error

	switch from {
	case FormatNP3:
		recipe, err = np3.Parse(input)
	case FormatXMP:
		recipe, err = xmp.Parse(input)
	}

	if err != nil {
		return nil, &ConversionError{
			Operation: "parse",
			Format:    from,
			Cause:     err,
		}
	}

	// Generate output from UniversalRecipe
	var output []byte

	switch to {
	case FormatNP3:
		output, err = np3.Generate(recipe)
	case FormatXMP:
		output, err = xmp.Generate(recipe)
	}

	if err != nil {
		return nil, &ConversionError{
			Operation: "generate",
			Format:    to,
			Cause:     err,
		}
	}

	return output, nil
}

// DetectFormat auto-detects the format of input data by examining file structure and magic bytes.
//
// Detection logic (in order of evaluation):
//   - NP3: Magic bytes "NCP" (ASCII) + minimum 300 bytes
//   - XMP: XML with x:xmpmeta wrapper - Adobe Lightroom CC/Camera Raw
//
// Returns:
//   - string: Detected format identifier ("np3" or "xmp")
//   - error: Error if format cannot be determined
//
// Performance: <1ms overhead
func DetectFormat(input []byte) (string, error) {
	// Check for NP3: magic bytes "NCP" + minimum size
	if len(input) >= 300 && bytes.HasPrefix(input, np3MagicBytes) {
		return FormatNP3, nil
	}

	// XMP: x:xmpmeta wrapper + crs: namespace (Adobe Lightroom)
	if bytes.Contains(input, []byte("x:xmpmeta")) {
		return FormatXMP, nil
	}

	return "", fmt.Errorf("unknown format: unable to detect from file content (size: %d bytes)", len(input))
}

// validateFormat checks if a format string is supported.
// Returns an error if the format is not one of: "np3", "xmp"
func validateFormat(format string) error {
	switch format {
	case FormatNP3, FormatXMP:
		return nil
	default:
		return fmt.Errorf("unsupported format: %q (must be %q or %q)",
			format, FormatNP3, FormatXMP)
	}
}
