package converter

import (
	"bytes"
	"fmt"
	"sort"

	"github.com/justin/recipe/internal/formats/np3"
	"github.com/justin/recipe/internal/formats/xmp"
	"github.com/justin/recipe/internal/models"
)

// Supported format identifiers
const (
	FormatNP3 = "np3"
	FormatXMP = "xmp"
)

// NP3 magic bytes (first 3 bytes: "NCP" in ASCII)
var np3MagicBytes = []byte{'N', 'C', 'P'}

// ConvertOptions controls optional behaviors during conversion.
type ConvertOptions struct {
	// FlattenCurves, when true and converting NP3→XMP, approximates the NP3 tone
	// curve as basic parameters (Contrast, Highlights, Shadows, Whites, Blacks) and
	// suppresses all curve fields in the output XMP. Ignored for all other paths.
	FlattenCurves bool
}

// Convert performs bidirectional conversion between supported photo editing recipe formats.
//
// It orchestrates the conversion flow: validate → parse → generate → wrap errors.
// The function is thread-safe and stateless, allowing concurrent conversions without race conditions.
//
// Supported formats:
//   - "np3": Nikon Picture Control binary format
//   - "xmp": Adobe Lightroom CC/Camera Raw XML format
//
// Supported conversions: NP3 ↔ XMP (2 conversion paths)
//
// Parameters:
//   - input: Raw bytes of the source format file
//   - from: Source format identifier ("np3" or "xmp"). Use empty string for auto-detection.
//   - to: Target format identifier ("np3" or "xmp")
//
// Returns:
//   - []byte: Generated bytes in the target format
//   - error: ConversionError with operation context, or nil on success
//
// Performance: Target <100ms per conversion, <5ms hub overhead
//
// Example:
//
//	np3Data, err := os.ReadFile("recipe.np3")
//	xmpData, err := converter.Convert(np3Data, "np3", "xmp")
//	if err != nil {
//	    var convErr *ConversionError
//	    if errors.As(err, &convErr) {
//	        fmt.Printf("Failed during %s: %v\n", convErr.Operation, convErr.Cause)
//	    }
//	}
func Convert(input []byte, from, to string) ([]byte, error) {
	return ConvertWithOptions(input, from, to, ConvertOptions{})
}

// ConvertWithOptions is like Convert but accepts ConvertOptions for opt-in behaviors.
func ConvertWithOptions(input []byte, from, to string, opts ConvertOptions) ([]byte, error) {
	// Auto-detect source format if not specified
	if from == "" {
		detectedFormat, err := DetectFormat(input)
		if err != nil {
			return nil, &ConversionError{
				Operation: "detect",
				Format:    "unknown",
				Cause:     err,
			}
		}
		from = detectedFormat
	}

	// Validate format strings
	if err := validateFormat(from); err != nil {
		return nil, &ConversionError{
			Operation: "validate",
			Format:    from,
			Cause:     err,
		}
	}
	if err := validateFormat(to); err != nil {
		return nil, &ConversionError{
			Operation: "validate",
			Format:    to,
			Cause:     err,
		}
	}

	// Parse input to UniversalRecipe
	var recipe *models.UniversalRecipe
	var err error

	switch from {
	case FormatNP3:
		recipe, err = np3.Parse(input)
	case FormatXMP:
		recipe, err = xmp.Parse(input)
	}

	if err != nil {
		return nil, &ConversionError{
			Operation: "parse",
			Format:    from,
			Cause:     err,
		}
	}

	// Apply optional pre-generation transforms
	if opts.FlattenCurves && ((from == FormatNP3 && to == FormatXMP) || (from == FormatXMP && to == FormatNP3)) {
		flattenCurvesToBasicParams(recipe)
	}

	// Generate output from UniversalRecipe
	var output []byte

	switch to {
	case FormatNP3:
		output, err = np3.Generate(recipe)
	case FormatXMP:
		output, err = xmp.Generate(recipe)
	}

	if err != nil {
		return nil, &ConversionError{
			Operation: "generate",
			Format:    to,
			Cause:     err,
		}
	}

	return output, nil
}

// DetectFormat auto-detects the format of input data by examining file structure and magic bytes.
//
// Detection logic (in order of evaluation):
//   - NP3: Magic bytes "NCP" (ASCII) + minimum 300 bytes
//   - XMP: XML with x:xmpmeta wrapper - Adobe Lightroom CC/Camera Raw
//
// Returns:
//   - string: Detected format identifier ("np3" or "xmp")
//   - error: Error if format cannot be determined
//
// Performance: <1ms overhead
func DetectFormat(input []byte) (string, error) {
	// Check for NP3: magic bytes "NCP" + minimum size
	if len(input) >= 300 && bytes.HasPrefix(input, np3MagicBytes) {
		return FormatNP3, nil
	}

	// XMP: x:xmpmeta wrapper + crs: namespace (Adobe Lightroom)
	if bytes.Contains(input, []byte("x:xmpmeta")) {
		return FormatXMP, nil
	}

	return "", fmt.Errorf("unknown format: unable to detect from file content (size: %d bytes)", len(input))
}

// flattenCurvesToBasicParams approximates the tone curve in recipe as basic parameters
// (Contrast, Highlights, Shadows, Whites, Blacks) and clears all curve fields.
//
// Priority: PointCurve (control points) is used when it has ≥2 points; otherwise
// ToneCurveParametric zone values are used. If neither is present, the recipe is unchanged.
//
// Derived values are added to any existing basic params and clamped to -100..+100,
// which is safe because NP3 cannot have both curves and basic params simultaneously
// (existing basic params will be at their zero defaults when a curve is present).
func flattenCurvesToBasicParams(recipe *models.UniversalRecipe) {
	if len(recipe.PointCurve) >= 2 {
		// Sort control points by input in case third-party NP3 tools store them unsorted
		pts := make([]models.ToneCurvePoint, len(recipe.PointCurve))
		copy(pts, recipe.PointCurve)
		sort.Slice(pts, func(i, j int) bool { return pts[i].Input < pts[j].Input })

		// Linear interpolation: find output value for a given input x
		interpolate := func(x int) int {
			if x <= pts[0].Input {
				return pts[0].Output
			}
			if x >= pts[len(pts)-1].Input {
				return pts[len(pts)-1].Output
			}
			for i := 1; i < len(pts); i++ {
				if x <= pts[i].Input {
					x0, y0 := pts[i-1].Input, pts[i-1].Output
					x1, y1 := pts[i].Input, pts[i].Output
					if x1 == x0 {
						return y0
					}
					return y0 + (y1-y0)*(x-x0)/(x1-x0)
				}
			}
			return pts[len(pts)-1].Output
		}

		// Sample curve and compute deviation from linear at key input points
		dev := func(x int) int { return interpolate(x) - x }
		scale := func(d int) int { return clampInt(d*100/128, -100, 100) }

		dev10 := dev(10)
		dev64 := dev(64)
		dev192 := dev(192)
		dev245 := dev(245)

		recipe.Blacks = clampInt(recipe.Blacks+scale(dev10), -100, 100)
		recipe.Shadows = clampInt(recipe.Shadows+scale(dev64), -100, 100)
		recipe.Highlights = clampInt(recipe.Highlights+scale(dev192), -100, 100)
		recipe.Whites = clampInt(recipe.Whites+scale(dev245), -100, 100)
		// Contrast from differential: positive S-curve → positive contrast
		contrastDev := (dev192 - dev64) / 2
		recipe.Contrast = clampInt(recipe.Contrast+scale(contrastDev), -100, 100)

	} else if recipe.ToneCurveShadows != 0 || recipe.ToneCurveDarks != 0 ||
		recipe.ToneCurveLights != 0 || recipe.ToneCurveHighlights != 0 {
		// Map parametric zone values to basic params
		s := recipe.ToneCurveShadows
		d := recipe.ToneCurveDarks
		l := recipe.ToneCurveLights
		h := recipe.ToneCurveHighlights

		recipe.Blacks = clampInt(recipe.Blacks+s, -100, 100)
		recipe.Shadows = clampInt(recipe.Shadows+(s+d)/2, -100, 100)
		recipe.Highlights = clampInt(recipe.Highlights+(l+h)/2, -100, 100)
		recipe.Whites = clampInt(recipe.Whites+h, -100, 100)
		recipe.Contrast = clampInt(recipe.Contrast+(l+h-s-d)/4, -100, 100)
	} else {
		// No curve data — nothing to flatten
		return
	}

	// Clear all curve fields (master + per-channel)
	recipe.PointCurve = nil
	recipe.PointCurveRed = nil
	recipe.PointCurveGreen = nil
	recipe.PointCurveBlue = nil
	recipe.ToneCurveShadows = 0
	recipe.ToneCurveDarks = 0
	recipe.ToneCurveLights = 0
	recipe.ToneCurveHighlights = 0
	recipe.ToneCurveShadowSplit = 0
	recipe.ToneCurveMidtoneSplit = 0
	recipe.ToneCurveHighlightSplit = 0
}

func clampInt(v, min, max int) int {
	if v < min {
		return min
	}
	if v > max {
		return max
	}
	return v
}

// validateFormat checks if a format string is supported.
// Returns an error if the format is not one of: "np3", "xmp"
func validateFormat(format string) error {
	switch format {
	case FormatNP3, FormatXMP:
		return nil
	default:
		return fmt.Errorf("unsupported format: %q (must be %q or %q)",
			format, FormatNP3, FormatXMP)
	}
}
