package converter

import (
	"bytes"
	"fmt"

	"github.com/justin/recipe/internal/formats/costyle"
	"github.com/justin/recipe/internal/formats/dcp"
	"github.com/justin/recipe/internal/formats/lrtemplate"
	"github.com/justin/recipe/internal/formats/np3"
	"github.com/justin/recipe/internal/formats/xmp"
	"github.com/justin/recipe/internal/models"
)

// Supported format identifiers
const (
	FormatNP3         = "np3"
	FormatXMP         = "xmp"
	FormatLRTemplate  = "lrtemplate"
	FormatCostyle     = "costyle"
	FormatCostylepack = "costylepack"
	FormatDCP         = "dcp"
)

// NP3 magic bytes (first 3 bytes: "NCP" in ASCII)
var np3MagicBytes = []byte{'N', 'C', 'P'}

// DCP magic bytes ("IIRC" - little-endian TIFF with DNG extension)
var dcpMagicBytes = []byte{0x49, 0x49, 0x52, 0x43}

// Convert performs bidirectional conversion between supported photo editing recipe formats.
//
// It orchestrates the conversion flow: validate → parse → generate → wrap errors.
// The function is thread-safe and stateless, allowing concurrent conversions without race conditions.
//
// Supported formats:
//   - "np3": Nikon Picture Control binary format
//   - "xmp": Adobe Lightroom CC/Camera Raw XML format
//   - "lrtemplate": Adobe Lightroom Classic Lua table format
//   - "costyle": Capture One preset XML format (XMP-style variant)
//   - "costylepack": Capture One preset bundle (ZIP archive of .costyle files)
//   - "dcp": Adobe DNG Camera Profile (binary TIFF format)
//
// Supported conversions: All format pairs (30 conversion paths total)
//
// Parameters:
//   - input: Raw bytes of the source format file
//   - from: Source format identifier ("np3", "xmp", "lrtemplate", "costyle", "costylepack", or "dcp"). Use empty string for auto-detection.
//   - to: Target format identifier ("np3", "xmp", "lrtemplate", "costyle", "costylepack", or "dcp")
//
// Returns:
//   - []byte: Generated bytes in the target format
//   - error: ConversionError with operation context, or nil on success
//
// Performance: Target <100ms per conversion, <5ms hub overhead
//
// Example:
//
//	np3Data, err := os.ReadFile("recipe.np3")
//	xmpData, err := converter.Convert(np3Data, "np3", "xmp")
//	if err != nil {
//	    var convErr *ConversionError
//	    if errors.As(err, &convErr) {
//	        fmt.Printf("Failed during %s: %v\n", convErr.Operation, convErr.Cause)
//	    }
//	}
func Convert(input []byte, from, to string) ([]byte, error) {
	// Auto-detect source format if not specified
	if from == "" {
		detectedFormat, err := DetectFormat(input)
		if err != nil {
			return nil, &ConversionError{
				Operation: "detect",
				Format:    "unknown",
				Cause:     err,
			}
		}
		from = detectedFormat
	}

	// Validate format strings
	if err := validateFormat(from); err != nil {
		return nil, &ConversionError{
			Operation: "validate",
			Format:    from,
			Cause:     err,
		}
	}
	if err := validateFormat(to); err != nil {
		return nil, &ConversionError{
			Operation: "validate",
			Format:    to,
			Cause:     err,
		}
	}

	// Parse input to UniversalRecipe
	var recipe *models.UniversalRecipe
	var err error

	switch from {
	case FormatNP3:
		recipe, err = np3.Parse(input)
	case FormatXMP:
		recipe, err = xmp.Parse(input)
	case FormatLRTemplate:
		recipe, err = lrtemplate.Parse(input)
	case FormatCostyle:
		recipe, err = costyle.Parse(input)
	case FormatCostylepack:
		// For costylepack, unpack and convert first recipe only
		// Note: Batch conversion of packs should be handled at CLI/TUI/Web level
		recipes, unpackErr := costyle.Unpack(input)
		if unpackErr != nil {
			err = unpackErr
		} else if len(recipes) == 0 {
			err = fmt.Errorf("empty costylepack bundle")
		} else {
			recipe = recipes[0] // Convert first recipe only
		}
	case FormatDCP:
		recipe, err = dcp.Parse(input)
	}

	if err != nil {
		return nil, &ConversionError{
			Operation: "parse",
			Format:    from,
			Cause:     err,
		}
	}

	// Generate output from UniversalRecipe
	var output []byte

	switch to {
	case FormatNP3:
		output, err = np3.Generate(recipe)
	case FormatXMP:
		output, err = xmp.Generate(recipe)
	case FormatLRTemplate:
		output, err = lrtemplate.Generate(recipe)
	case FormatCostyle:
		output, err = costyle.Generate(recipe)
	case FormatCostylepack:
		// For costylepack target, pack single recipe into bundle
		// Note: Batch packing should be handled at CLI/TUI/Web level
		filename := "preset.costyle"
		if recipe.Name != "" {
			filename = recipe.Name + ".costyle"
		}
		output, err = costyle.Pack([]*models.UniversalRecipe{recipe}, []string{filename})
	case FormatDCP:
		output, err = dcp.Generate(recipe)
	}

	if err != nil {
		return nil, &ConversionError{
			Operation: "generate",
			Format:    to,
			Cause:     err,
		}
	}

	return output, nil
}

// DetectFormat auto-detects the format of input data by examining file structure and magic bytes.
//
// Detection logic (in order of evaluation):
//   - NP3: Magic bytes "NCP" (ASCII) + minimum 300 bytes
//   - DCP: Magic bytes "IIRC" (0x49 0x49 0x52 0x43) - Adobe DNG Camera Profile
//   - Costylepack: ZIP magic bytes (PK\x03\x04) - Capture One preset bundles
//   - lrtemplate: Lua table syntax ("s = {") - Lightroom Classic presets
//   - Costyle: XML with <SL Engine=> tag - Capture One individual presets
//   - XMP: XML with x:xmpmeta wrapper - Adobe Lightroom CC/Camera Raw
//
// Returns:
//   - string: Detected format identifier ("np3", "xmp", "lrtemplate", "costyle", "costylepack", or "dcp")
//   - error: Error if format cannot be determined
//
// Performance: <1ms overhead
//
// Example:
//
//	data, _ := os.ReadFile("unknown_recipe")
//	format, err := converter.DetectFormat(data)
//	if err != nil {
//	    fmt.Println("Unknown format")
//	}
func DetectFormat(input []byte) (string, error) {
	// Check for NP3: magic bytes "NCP" + minimum size
	if len(input) >= 300 && bytes.HasPrefix(input, np3MagicBytes) {
		return FormatNP3, nil
	}

	// Check for DCP: magic bytes "IIRC" (little-endian TIFF with DNG extension)
	if len(input) >= 8 && bytes.HasPrefix(input, dcpMagicBytes) {
		return FormatDCP, nil
	}

	// Check for costylepack: ZIP magic bytes (PK\x03\x04)
	// Costylepack is a ZIP archive containing .costyle files
	zipMagic := []byte{0x50, 0x4B, 0x03, 0x04}
	if bytes.HasPrefix(input, zipMagic) {
		return FormatCostylepack, nil
	}

	// Check for lrtemplate: Lua table syntax (check before XML to avoid false positives)
	trimmed := bytes.TrimSpace(input)
	if bytes.HasPrefix(trimmed, []byte("s = {")) {
		return FormatLRTemplate, nil
	}

	// Check for XML-based formats (XMP and Costyle)
	// Costyle uses Capture One's SL (Style Layer) format with <SL Engine=> tag
	// XMP uses Adobe's XMP metadata format with x:xmpmeta wrapper
	if bytes.Contains(input, []byte("<SL Engine=")) || bytes.Contains(input, []byte("<SL ")) {
		return FormatCostyle, nil
	}

	// XMP: x:xmpmeta wrapper + crs: namespace (Adobe Lightroom)
	if bytes.Contains(input, []byte("x:xmpmeta")) {
		return FormatXMP, nil
	}

	return "", fmt.Errorf("unknown format: unable to detect from file content (size: %d bytes)", len(input))
}

// validateFormat checks if a format string is supported.
// Returns an error if the format is not one of: "np3", "xmp", "lrtemplate", "costyle", "costylepack", "dcp"
func validateFormat(format string) error {
	switch format {
	case FormatNP3, FormatXMP, FormatLRTemplate, FormatCostyle, FormatCostylepack, FormatDCP:
		return nil
	default:
		return fmt.Errorf("unsupported format: %q (must be %q, %q, %q, %q, %q, or %q)",
			format, FormatNP3, FormatXMP, FormatLRTemplate, FormatCostyle, FormatCostylepack, FormatDCP)
	}
}
